# Generated by Django 2.2 on 2020-06-17 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slides', '0002_auto_20200617_0127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slide',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='slide',
            old_name='modified',
            new_name='updated_at',
        ),
    ]
